# Generated by Django 4.1.2 on 2023-02-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_order_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
